### PR TITLE
Fix VC14 x64 crashes

### PR DESCRIPTION
**Pull request by Jan-E**
New PR as a replacement for https://github.com/Sean-Der/phpredis/pull/4

Some test failures on x64 - https://github.com/Sean-Der/phpredis/pull/4#issuecomment-139855362 -, but no more crashes.

### CODE REVIEW

**Comment by Jan-E** [comment]
I do not know if the casts to long are needed:

    start = (long)z_start;
    end = (long)z_end;

Maybe we can use zend_long's directly. This works, but some cleanup might be needed.

**Comment by Jan-E** [comment]
@Sean-Der  Is there any reason why you did not merge this PR?

**Comment by Sean-Der** [comment]
Hey @Jan-E really sorry I didn't comment back sooner! Juggling one to many things today.
Really nice catch on argument passing being wrong, I think that is the root of the problem. 

If you have the time, would you mind/want to go through all the calls to zend_parse* and make sure they line up with the [Parameter Passing API](http://lxr.php.net/xref/PHP_TRUNK/README.PARAMETER_PARSING_API#53) ?

**Comment by Jan-E** [comment]
> If you have the time, would you mind/want to go through all the calls to zend_parse* and make sure they line up with the Parameter Passing API ?

Sorry, do not have the time either.

**Comment by Sean-Der** [comment]
Hey!
Sorry to make a hassle, but would you mind reopening this against the php7 branch on the official phpredis repo? I don't want to lose the config.w32 change.
I am going to delete my fork after that is opened/merged.

thanks!

**Comment by Jerry-Shaw** [comment]
Good job, guys, @Sean-Der  & @Jan-E .

The new php7 branch on the official phpredis works, build with VS2015, PHP7 RC2 x64, on Win10 x64. Everything looks good on my search engine, no crashes any more. 

I ran the full tests after fixing some code errors in the php tests, changing all "dirname($_SERVER['PHP_SELF'])" to "dirname(__FILE__)". I don't know why "$_SERVER['PHP_SELF']" didn't work on my PC, showing the error if I don't modified the code:

PHP Warning:  require_once(/tests/TestSuite.php): failed to open stream: No such file or directory in E:\Sites\ooBase\tests\TestRedis.php on line 3
PHP Fatal error:  require_once(): Failed opening required '/tests/TestSuite.php' (include_path='.;C:\php\pear') in E:\Sites\ooBase\tests\TestRedis.php on line 3

Then I got:

PHP Notice:  Redis::get(): send of 36 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.
 in E:\Sites\ooBase\tests\RedisTest.php on line 4460

Then, I skipped the lines 4457, 425, 435 of the sleep() function, I got the results:

Note: these tests might take up to a minute. Don't worry :-)
Testing class Redis
testMinimumVersion         [PASSED]
testPing                   [PASSED]
testPipelinePublish        [PASSED]
testPubSub                 [PASSED]
testBitsets                [PASSED]
testBitPos                 [PASSED]
test1000                   [PASSED]
testEcho                   [PASSED]
testErr                    [PASSED]
testSet                    [PASSED]
testExtendedSet            [PASSED]
testGetSet                 [PASSED]
testRandomKey              [PASSED]
testRename                 [PASSED]
testRenameNx               [PASSED]
testMultiple               [PASSED]
testMultipleBin            [PASSED]
testSetTimeout             [FAILED]
testExpireAt               [FAILED]
testSetEx                  [PASSED]
testSetNX                  [PASSED]
testExpireAtWithLong       [FAILED]
testIncr                   [PASSED]
testIncrByFloat            [PASSED]
testDecr                   [PASSED]
testExists                 [PASSED]
testGetKeys                [PASSED]
testDelete                 [PASSED]
testType                   [PASSED]
testStr                    [PASSED]
testlPop                   [PASSED]
testrPop                   [PASSED]
testblockingPop            [PASSED]
testllen                   [PASSED]
testlPopx                  [PASSED]
testltrim                  [PASSED]
testSortPrefix             [PASSED]
testSortAsc                [PASSED]
testSortDesc               [PASSED]
testlGet                   [PASSED]
testlrem                   [PASSED]
testsAdd                   [PASSED]
testscard                  [PASSED]
testsrem                   [PASSED]
testsMove                  [PASSED]
testsPop                   [PASSED]
testsRandMember            [PASSED]
testSRandMemberWithCount   [PASSED]
testsismember              [PASSED]
testsmembers               [PASSED]
testlSet                   [PASSED]
testsInter                 [PASSED]
testsInterStore            [PASSED]
testsUnion                 [PASSED]
testsUnionStore            [PASSED]
testsDiff                  [PASSED]
testsDiffStore             [PASSED]
testlrange                 [PASSED]
testdbSize                 [PASSED]
testttl                    [PASSED]
testPersist                [PASSED]
testClient                 [PASSED]
testSlowlog                [PASSED]
testWait                   [PASSED]
testInfo                   [PASSED]
testInfoCommandStats       [PASSED]
testSelect                 [PASSED]
testMset                   [PASSED]
testMsetNX                 [PASSED]
testRpopLpush              [PASSED]
testBRpopLpush             [PASSED]
testZAddFirstArg           [PASSED]
testZX                     [PASSED]
testHashes                 [PASSED]
testSetRange               [PASSED]
testObject                 [PASSED]
testMultiExec              [PASSED]
testFailedTransactions     [PASSED]
testPipeline               [PASSED]
testDifferentTypeString    [PASSED]
testDifferentTypeList      [PASSED]
testDifferentTypeSet       [PASSED]
testDifferentTypeSortedSet [PASSED]
testDifferentTypeHash      [PASSED]
testSerializerPHP          [PASSED]
testSerializerIGBinary     [PASSED]
testDumpRestore            [PASSED]
testGetLastError           [PASSED]
testScript                 [PASSED]
testEval                   [PASSED]
testEvalSHA                [PASSED]
testSerialize              [PASSED]
testUnserialize            [PASSED]
testPrefix                 [PASSED]
testReconnectSelect        [PASSED]
testTime                   [PASSED]
testReadTimeoutOption      [PASSED]
testIntrospection          [PASSED]
testScan                   [PASSED]
testHScan                  [PASSED]
testSScan                  [PASSED]
testZScan                  [PASSED]
testPFCommands             [PASSED]
testRawCommand             [PASSED]


Assertion failed ( !== value): E:\Sites\ooBase\tests\RedisTest.php:426 (testSetTimeout)
Assertion failed ( !== value): E:\Sites\ooBase\tests\RedisTest.php:436 (testExpireAt)
Assertion failed: E:\Sites\ooBase\tests\RedisTest.php:461 (testExpireAtWithLong)
Assertion failed: E:\Sites\ooBase\tests\RedisTest.php:462 (testExpireAtWithLong)

Only of the three I modified failed, all are the expire function tests.

I'll make more to see the TTL if it works or not.

**Comment by Jerry-Shaw** [comment]
Functions "testSetTimeout", "testExpireAt" works fine with my own simple codes.

Only testReconnectSelect showed the same notice both on Redis Client 2.8.2103 & 3.0.300-alpha3, cannot get connected again after the timeout set:

PHP Notice:  Redis::get(): send of 20 bytes failed with errno=10054 An existing connection was forcibly closed by the remote host.
 in E:\Sites\ooBase\test.php on line 26
PHP Fatal error:  Uncaught RedisException: read error on connection in E:\Sites\ooBase\test.php:26

**Comment by Sean-Der** [comment]
Holy shit that makes me so happy, really was curious where those segfaults were coming from (@Jan-E discovered the long/zend_long issue and that got it in!)

Were you building with this patch and/or have you tried building with [HEAD](https://github.com/phpredis/phpredis/tree/php7) yet?

**Comment by Jerry-Shaw** [comment]
Ah... I just build it from https://github.com/phpredis/phpredis/tree/php7, no more changes.

Is there any new update comments?

**Comment by Jan-E** [comment]
I checked PHP 5.3 & 5.4 x86 and PHP 5.6 x64: they all generate the same errors as PHP 7 now. Ergo: the php7 branch is as good as the previous branches are.

I will reopen the remaining patches against the php7 branch of phpredis/phpredis.

**Pull request closed without merging**
