### PR TITLE
Fix inconsistent dll linkage, improve get exception base

### PR DESCRIPTION
**Pull request by Jan-E**
@Sean-Der 
The inconsistent dll linkage was bothering me. I improved get exception base, using https://github.com/php/php-src/blob/master/ext/pdo/pdo.c#L80 as example.
Then I remembered it had to be PHP_REDIS_API in stead of PHPAPI for Windows.

Some other fixes are included in this PR. Will post test results later. It is 1:25 AM on this side of the Ocean.

### CODE REVIEW

**Comment by Sean-Der** [comment]
All the tests still pass on Unix, LGTM! Merged

**Comment by Jan-E** [comment]
I added some additional commits after your merge. Now looking into gettimeofday.

**Comment by Jerry-Shaw** [comment]
Hi, @Jan-E , does the latest php7-new branch crashes the CGI on your PC when testing? I cannot tell if there were problems when compiling or testing. There might be something wrong in my dll?

I compiled the one on windows 10 x64 using VS 2015 12 hours ago, and found zRevRange function made crashes. It might be different on Unix and windows, @Sean-Der , so, it might be caused here.

I got busy today, so reply later and watching you guys.

**Comment by Jan-E** [comment]
@Sean-Der I will have to check if we are on par now. If so, I will close this PR.

BTW: I have got a 47GB windows7.vdi with a complete VC14/PHP7 build environment. It mumbles something that the activation period has expired, but as a Virtualbox for building PHP7 it works fine. Interested?

**Comment by Jan-E** [comment]
Closing. See new PR.

**Pull request closed without merging**
